### ISSUE TITLE
Your script does not work anymore

### ISSUE THREAD

**Issue by samip5** [kauppine/edgerouter-telia6rd#1]
Running on EdgeOS version 2.0.6.

It does not say anything anywhere and config updates are not appearing.

**Comment by kauppine** [comment]
Thanks for informing, I noticed the same after upgrading to 2.0.7
I did update the script and the documentation and tried it on clean Edgerouter.
If you could try it out and report whether it works or not would be awesome

**Comment by samip5** [comment]
> Thanks for informing, I noticed the same after upgrading to 2.0.7
> I did update the script and the documentation and tried it on clean Edgerouter.
> If you could try it out and report whether it works or not would be awesome

Unfortunately, I'm not in a position where I can test it anymore. I don't reside in a building with Telia internet anymore.

**Comment by kauppine** [comment]
9cea609fbcb16c71006573babf6c53e4f7004d61 should fix this.
