### ISSUE TITLE
This does not work for me

### ISSUE THREAD

**Issue by pianoquintet** [kauppine/edgerouter-telia6rd#2]
I followed the instructions on my ER-X SFP runing firmware 2.0.8 - except that my WAN is on eth5, so I modified the two "set interfaces" commands accordingly (while I did not find anything in the script which had to be modified).

The script does not work for me: no IPV6 address obtained, no tunnel created, no firewall rules added.

I tried running these commands to troubleshoot:

(i) /etc/dhcp3/dhclient-exit-hooks.d/option-6rd
   This returns "Permission Denied"

(ii) sudo /etc/dhcp3/dhclient-exit-hooks.d/option-6rd
   This returns"command not found"

I then did a chmod +x for the script and ran again sudo /etc/dhcp3/dhclient-exit-hooks.d/option-6rd.
   This returned "No such file or directory".

Please help.

Thank you,

**Comment by kauppine** [comment]
> I tried running these commands to troubleshoot:
> 
> (i) /etc/dhcp3/dhclient-exit-hooks.d/option-6rd
> This returns "Permission Denied"
> 
> (ii) sudo /etc/dhcp3/dhclient-exit-hooks.d/option-6rd
> This returns"command not found"
> 
> I then did a chmod +x for the script and ran again sudo /etc/dhcp3/dhclient-exit-hooks.d/option-6rd.
> This returned "No such file or directory".

This is expected behaviour, as the script is owned by root. Additionally, it does not have a main-function and therefore will only run when run through DHCP.

Did you install the ipv6calc-package as the script will not work without it?
If it is not installed you should see errors in Edgerouter's log.

Also, are you sure that your ISP offers 6rd options through DHCP? Atleast in Finland Telia seems to be the only ISP to even support 6rd.

**Comment by pianoquintet** [comment]
The answer is yes to both.  I also did a packet sniff and the isp responds to the 212 requests with the ipv6 info. 

> On 31 Jan 2020, at 10:30, kauppine <notifications@github.com> wrote:
> 

﻿
I tried running these commands to troubleshoot:

(i) /etc/dhcp3/dhclient-exit-hooks.d/option-6rd
This returns "Permission Denied"

(ii) sudo /etc/dhcp3/dhclient-exit-hooks.d/option-6rd
This returns"command not found"

I then did a chmod +x for the script and ran again sudo /etc/dhcp3/dhclient-exit-hooks.d/option-6rd.
This returned "No such file or directory".
This is expected behaviour, as the script is owned by root. Additionally, it does not have a main-function and therefore will only run when run through DHCP.

Did you install the ipv6calc-package as the script will not work without it?
If it is not installed you should see errors in Edgerouter's log.

Also, are you sure that your ISP offers 6rd options through DHCP? Atleast in Finland Telia seems to be the only ISP to even support 6rd.

**Comment by kauppine** [comment]
Do you see anything related to 6rd in the logs?

**Comment by pianoquintet** [comment]
Which log file should I look at?

> On 31 Jan 2020, at 16:01, kauppine <notifications@github.com> wrote:
> 

﻿
Do you see anything related to 6rd in the logs?

**Comment by kauppine** [comment]
/var/log/messages

This can be also viewed with command "show log".

**Comment by kauppine** [comment]
9cea609fbcb16c71006573babf6c53e4f7004d61 should fix this.
